# -*- coding: utf-8 -*-
"""Calculadora_Figuras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZTuZ5Zhr_oyVxzj7a-j-S8LfeCWcM_4
"""

from math import pi, sqrt

print("===CALCULADORA DE FIGURAS===")
print("1. Cubo")
print("2. Prisma")
print("3. Piramide")
print("4. Cilindro")
print("5. Cono")
print("6. Esfera")

figura = int(input("Selecciona una figura (1-6): "))

print("_*_*_*_Menú de opciones_*_*_*_")
print("1. Calcular el área")
print("2. Calcular volumen")
print("3. Calcular ambos")
print("4. Salir")

opcion = int(input("Selecciona una opción (1-4): "))

if opcion == 4:
    print("¡Hasta luego!")
else:
    if figura == 1:  # CUBO
        lado = float(input("Ingresa la longitud del lado: "))
        if opcion == 1:
            area = 6 * lado ** 2
            print(f"Área del cubo: {area:.2f}")
        elif opcion == 2:
            volumen = lado ** 3
            print(f"Volumen del cubo: {volumen:.2f}")
        elif opcion == 3:
            area = 6 * lado ** 2
            volumen = lado ** 3
            print(f"Área del cubo: {area:.2f}")
            print(f"Volumen del cubo: {volumen:.2f}")

    elif figura == 2:  # PRISMA
        largo = float(input("Ingresa el largo: "))
        ancho = float(input("Ingresa el ancho: "))
        altura = float(input("Ingresa la altura: "))
        if opcion == 1:
            area = 2 * (largo * ancho + largo * altura + ancho * altura)
            print(f"Área del prisma: {area:.2f}")
        elif opcion == 2:
            volumen = largo * ancho * altura
            print(f"Volumen del prisma: {volumen:.2f}")
        elif opcion == 3:
            area = 2 * (largo * ancho + largo * altura + ancho * altura)
            volumen = largo * ancho * altura
            print(f"Área del prisma: {area:.2f}")
            print(f"Volumen del prisma: {volumen:.2f}")

    elif figura == 3:  # PIRAMIDE
        base = float(input("Ingresa la longitud de la base: "))
        altura = float(input("Ingresa la altura: "))
        if opcion == 1:
            area_base = base ** 2
            apotema = sqrt((base/2)**2 + altura**2)
            area_lateral = 4 * (base * apotema / 2)
            area = area_base + area_lateral
            print(f"Área de la pirámide: {area:.2f}")
        elif opcion == 2:
            volumen = (base ** 2 * altura) / 3
            print(f"Volumen de la pirámide: {volumen:.2f}")
        elif opcion == 3:
            area_base = base ** 2
            apotema = sqrt((base/2)**2 + altura**2)
            area_lateral = 4 * (base * apotema / 2)
            area = area_base + area_lateral
            volumen = (base ** 2 * altura) / 3
            print(f"Área de la pirámide: {area:.2f}")
            print(f"Volumen de la pirámide: {volumen:.2f}")

    elif figura == 4:  # CILINDRO
        radio = float(input("Ingresa el radio: "))
        altura = float(input("Ingresa la altura: "))
        if opcion == 1:
            area = 2 * pi * radio * (radio + altura)
            print(f"Área del cilindro: {area:.2f}")
        elif opcion == 2:
            volumen = pi * radio ** 2 * altura
            print(f"Volumen del cilindro: {volumen:.2f}")
        elif opcion == 3:
            area = 2 * pi * radio * (radio + altura)
            volumen = pi * radio ** 2 * altura
            print(f"Área del cilindro: {area:.2f}")
            print(f"Volumen del cilindro: {volumen:.2f}")

    elif figura == 5:  # CONO
        radio = float(input("Ingresa el radio: "))
        altura = float(input("Ingresa la altura: "))
        if opcion == 1:
            generatriz = sqrt(radio**2 + altura**2)
            area = pi * radio * (radio + generatriz)
            print(f"Área del cono: {area:.2f}")
        elif opcion == 2:
            volumen = (pi * radio ** 2 * altura) / 3
            print(f"Volumen del cono: {volumen:.2f}")
        elif opcion == 3:
            generatriz = sqrt(radio**2 + altura**2)
            area = pi * radio * (radio + generatriz)
            volumen = (pi * radio ** 2 * altura) / 3
            print(f"Área del cono: {area:.2f}")
            print(f"Volumen del cono: {volumen:.2f}")

    elif figura == 6:  # ESFERA
        radio = float(input("Ingresa el radio: "))
        if opcion == 1:
            area = 4 * pi * radio ** 2
            print(f"Área de la esfera: {area:.2f}")
        elif opcion == 2:
            volumen = (4/3) * pi * radio ** 3
            print(f"Volumen de la esfera: {volumen:.2f}")
        elif opcion == 3:
            area = 4 * pi * radio ** 2
            volumen = (4/3) * pi * radio ** 3
            print(f"Área de la esfera: {area:.2f}")
            print(f"Volumen de la esfera: {volumen:.2f}")

    else:
        print("Figura no válida. Debe ser un número del 1 al 6.")