# -*- coding: utf-8 -*-
"""Calculadora_letras.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drikbUAOS57q1OIwXTbEHXmMSU05wT49
"""

name=input("¿Cuál es tu nombre?")
print("¡Hola! ,"+name)

print("===ANALIZANDO TEXTO===")
print("1. Contar número de caracteres")
print("2. Convertir a mayúsculas")
print("3. Convertir a minúsculas")
print("4. Contar cuantas veces aparece una letra")
print("5. Reemplazar una letra por otra")
print("6. Unir cada letra con un guion")
print("7. Sumar la longitud del string")
print("8. Salir")

texto = input("Ingrese la palabra o texto: ")
opcion = int(input("Elige una opción (1-8): "))

if opcion == 1:
    # Contar caracteres (incluyendo espacios)
    print(f"Número de caracteres: {len(texto)}")

elif opcion == 2:
    print(texto.upper())

elif opcion == 3:
    print(texto.lower())

elif opcion == 4:
    letra = input("Ingresa la letra a contar: ")
    cantidad = texto.count(letra)
    print(f"La letra '{letra}' aparece {cantidad} veces")

elif opcion == 5:
    letra_original = input("Letra a reemplazar: ")
    letra_nueva = input("Nueva letra: ")
    nuevo_texto = texto.replace(letra_original, letra_nueva)
    print(nuevo_texto)

elif opcion == 6:
    texto_con_guiones = "-".join(texto)
    print(texto_con_guiones)

elif opcion == 7:
    print(f"Longitud del texto: {len(texto)} caracteres")

elif opcion == 8:
    print("Saliendo del programa...")

else:
    print("Opción no válida. Debe ser un número del 1 al 8")

print("Adios...")