# -*- coding: utf-8 -*-
"""basta_final_version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I0jAPBrEiNgyiuYnSpz47uZLeoipohhL
"""

#import random #Nos va a importar TODA la librería
from random import choice
from time import sleep
from os import system

#Lista de las categorías que debemos adivinar en el juego
categorias = {}
letras = "abcdefghijklmnopqrstuvwxyz"
puntosTotales = 0
contadorRondas = 0

print("\n" + "="*50)
print("¡BIENVENIDO AL ASISTENTE DEL JUEGO BASTA!")
print("="*50)
print("\nConfigura las categorías de tu juego Basta\n")

contadorCategoria = 0
while True:
    contadorCategoria += 1
    categoria = input(f"Ingresa categoría {contadorCategoria} (deja vacío para terminar): ")

    if categoria == "":
        if contadorCategoria == 1:
            print("¡Debes ingresar al menos una categoría!")
            contadorCategoria -= 1
            continue
        break

    categorias[contadorCategoria] = categoria.capitalize()
    print(f"Categoría '{categoria.capitalize()}' agregada.")

print(f"\n¡Perfecto! Tienes {len(categorias)} categorías configuradas.")
sleep(2)
system("clear")

"""
        1. Elegir la letra para jugar
        2. Mostrar categorías
        3. Preguntar los valores de las categorías
        4. Preguntar puntos
        5. Sumar puntos a Totales
        6. Preguntar si quiere seguir jugando
"""

while True:
    if not letras:
        print("\n¡Has usado todas las letras del abecedario!")
        break

    contadorRondas += 1
    #Elegir una letra random del abecedario
    letra = choice(letras)
    letras = letras.replace(letra,"")

    print("\n" + "="*50)
    print(f"RONDA {contadorRondas} - LETRA: {letra.upper()}")
    print("="*50)

    valoresCategorias = categorias.values()
    print("Categorías: ", " | ".join(map(str, valoresCategorias)))
    print("\nPensando...")
    sleep(2)

    palabras = {} #Diccionario para almacenar las palabras que ingrese el usuario por categoría

    print("\nIngresa tus respuestas (escribe 'salir' para terminar el juego):")

    salir_juego = False
    for llave, categoria in categorias.items():
        while True:
            palabra = input(f"\n{categoria} con la letra {letra.upper()}: ").strip()

            if palabra.lower() == "salir":
                salir_juego = True
                break
            elif palabra == "":
                print("Debes ingresar una palabra. Intenta nuevamente.")
                continue
            elif not palabra[0].lower() == letra.lower():
                print(f"La palabra no empieza con '{letra.upper()}'. ¿Estás seguro? (s/n)")
                confirmacion = input().lower()
                if confirmacion != 's':
                    continue

            palabras[categoria] = palabra.capitalize()
            break

        if salir_juego:
            break

    if salir_juego:
        break

    # Mostrar resumen de la ronda
    print("\n" + "="*50)
    print("RESUMEN DE LA RONDA")
    print("="*50)
    for categoria, palabra in palabras.items():
        print(f"{categoria} --> {palabra}")

    # Sistema de puntos mejorado
    print("\n" + "="*50)
    print("PUNTUACION")
    print("="*50)
    puntosRonda = 0
    print("Ingresa los puntos obtenidos en cada categoría:")

    for llave, categoria in categorias.items():
        while True:
            puntosCategoria = input(f"\nPuntos para {categoria}: ").strip()

            if puntosCategoria == "":
                puntosCategoria = 0
                break
            elif puntosCategoria.isnumeric():
                puntosCategoria = int(puntosCategoria)
                if puntosCategoria >= 0:
                    break
                else:
                    print("Los puntos no pueden ser negativos.")
            else:
                print("Ingresa solo números. Intenta nuevamente.")
                continue

        puntosRonda += puntosCategoria
        print(f"Puntos acumulados en esta ronda: {puntosRonda}")

    puntosTotales += puntosRonda

    print(f"\nPuntos de esta ronda: {puntosRonda}")
    print(f"Puntos totales: {puntosTotales}")

    # Mostrar progreso
    print(f"\nEstadísticas:")
    print(f"- Rondas jugadas: {contadorRondas}")
    print(f"- Letras disponibles: {len(letras)}")
    print(f"- Puntos promedio por ronda: {puntosTotales/contadorRondas:.1f}")

    sleep(4)
    system("clear")

    if letras:
        continuar = input("\n¿Quieres jugar otra ronda? (s/n): ").lower()
        if continuar != 's':
            break
    else:
        print("\n¡No hay más letras disponibles!")
        break

# Pantalla final
print("\n" + "="*50)
print("JUEGO TERMINADO")
print("="*50)
print(f"RESUMEN FINAL:")
print(f"- Total de rondas: {contadorRondas}")
print(f"- Puntos totales: {puntosTotales}")
print(f"- Puntos promedio por ronda: {puntosTotales/contadorRondas:.1f}")

if puntosTotales > 100:
    print("¡Excelente puntuación! Eres un campeón del Basta!")
elif puntosTotales > 50:
    print("¡Buena puntuación! Sigue practicando.")
else:
    print("Sigue practicando, la próxima vez lo harás mejor.")

# Nuevo mensaje de despedida
print("\n" + "*" * 60)
print("¡Fue genial jugar contigo!")
print("Espero que hayas disfrutado tanto como yo de este juego.")
print("Recuerda practicar con nuevas categorías para mejorar.")
print("¡Te espero en la próxima partida de Basta!")
print("*" * 60)