# -*- coding: utf-8 -*-
"""Juego_ahorcado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pFpktFAbSXCv6nZ74twNlGXP2MSctoFj
"""

import random

puntos_totales = 0
partidas_ganadas = 0
partidas_perdidas = 0

print("¡Bienvenido al juego del ahorcado!")
print("=" * 40)

while True:
    palabras = ['gato', 'perro', 'elefante', 'jirafa', 'tigre', 'leon', 'mono', 'cebra', 'oso', 'panda']
    palabra_secreta = random.choice(palabras)
    vidas = 3
    letras_adivinadas = ['_'] * len(palabra_secreta)
    letras_incorrectas = []

    print(f"\n--- Nueva Partida ---")
    print(f"Puntos totales: {puntos_totales}")
    print(f"Partidas ganadas: {partidas_ganadas}")
    print(f"Partidas perdidas: {partidas_perdidas}")
    print("Tienes 3 vidas para adivinar la palabra.")

    while vidas > 0 and '_' in letras_adivinadas:
        print("\n" + ' '.join(letras_adivinadas))
        print(f"Vidas restantes: {vidas}")
        if letras_incorrectas:
            print(f"Letras incorrectas: {', '.join(letras_incorrectas)}")

        letra = input("Ingresa una letra: ").lower()

        if len(letra) != 1 or not letra.isalpha():
            print("Por favor ingresa solo una letra válida.")
            continue

        if letra in letras_adivinadas or letra in letras_incorrectas:
            print("Ya habías intentado con esa letra.")
            continue

        if letra in palabra_secreta:
            for i in range(len(palabra_secreta)):
                if palabra_secreta[i] == letra:
                    letras_adivinadas[i] = letra
            print(f"¡Correcto! La letra '{letra}' está en la palabra.")
        else:
            vidas -= 1
            letras_incorrectas.append(letra)
            print(f"La letra '{letra}' no está en la palabra. Pierdes una vida.")

    # Calcular puntos de esta partida
    if '_' not in letras_adivinadas:
        puntos_partida = vidas * 10  # 10 puntos por cada vida restante
        puntos_totales += puntos_partida
        partidas_ganadas += 1
        print(f"\n¡Felicidades! Adivinaste la palabra: {palabra_secreta}")
        print(f"Ganaste {puntos_partida} puntos por esta partida.")
    else:
        partidas_perdidas += 1
        print(f"\n¡Game Over! La palabra era: {palabra_secreta}")

    print(f"\n--- Resumen de la Partida ---")
    print(f"Puntos ganados en esta partida: {puntos_partida if '_' not in letras_adivinadas else 0}")
    print(f"Puntos totales: {puntos_totales}")
    print(f"Partidas ganadas: {partidas_ganadas}")
    print(f"Partidas perdidas: {partidas_perdidas}")

    # Preguntar si quiere seguir jugando
    while True:
        jugar_de_nuevo = input("\n¿Quieres jugar otra partida? (s/n): ").lower()
        if jugar_de_nuevo in ['s', 'n', 'si', 'no']:
            break
        print("Por favor ingresa 's' para sí o 'n' para no.")

    if jugar_de_nuevo == 'n' or jugar_de_nuevo == 'no':
        break

# Mensaje final
print("\n" + "=" * 50)
print("¡Gracias por jugar al Ahorcado!")
print(f"Puntuación final: {puntos_totales} puntos")
print(f"Partidas ganadas: {partidas_ganadas}")
print(f"Partidas perdidas: {partidas_perdidas}")

if puntos_totales > 50:
    print("¡Eres un experto en el Ahorcado!")
elif puntos_totales > 20:
    print("¡Buen trabajo! Sigue practicando.")
else:
    print("Sigue intentándolo, mejorarás con la práctica.")

print("¡Hasta la próxima!")
print("=" * 50)